ALTER TABLE files
  ADD COLUMN IF NOT EXISTS size_bytes BIGINT NULL,
  ADD COLUMN IF NOT EXISTS sha256 CHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'pending_upload';

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS password_changed_at DATETIME NULL;
