CREATE TABLE IF NOT EXISTS fc_cert_reemplazos (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  anio        SMALLINT     NOT NULL,
  seccion     ENUM('FRANCOS_COMPENSATORIOS','CERTIFICACION_SERVICIOS','REEMPLAZOS_GUARDIA') NOT NULL,
  agente      VARCHAR(200) NOT NULL,
  enero       VARCHAR(100),
  febrero     VARCHAR(100),
  marzo       VARCHAR(100),
  abril       VARCHAR(100),
  mayo        VARCHAR(100),
  junio       VARCHAR(100),
  julio       VARCHAR(100),
  agosto      VARCHAR(100),
  septiembre  VARCHAR(100),
  octubre     VARCHAR(100),
  noviembre   VARCHAR(100),
  diciembre   VARCHAR(100),
  creado_por  INT          NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP    NULL,
  INDEX idx_fcr_anio_seccion (anio, seccion),
  INDEX idx_fcr_agente (agente(50))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
