/* eslint-disable */
// @generated by scripts/routes/genAutoRoutesManifest.mjs
// NO EDITAR A MANO. Editá los archivos *.routes.ts en src/routes/auto/

export type AutoRouteEntry = {
  /** basePath exportado por el módulo (ej: "/certificados") */
  basePath: string;
  /** loader dinámico al módulo .routes.ts */
  load: () => Promise<{ basePath: string; buildRouter: (ctx: any) => any }>;
};

export const manifest: AutoRouteEntry[] = [
];

export const __manifestCount = manifest.length;
