FROM node:20-alpine
WORKDIR /app
COPY package.json /app/package.json
COPY api/package.json /app/api/package.json
COPY worker/package.json /app/worker/package.json
COPY agent/package.json /app/agent/package.json
COPY shared/package.json /app/shared/package.json
RUN npm i --workspaces --include-workspace-root
COPY . /app
WORKDIR /app/api
RUN npm run build
EXPOSE 3000
CMD ["npm","run","start"]
